/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddChatForm: typeof import('./components/AddChatForm.vue')['default']
    AddChatModal: typeof import('./components/AddChatModal.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseForm: typeof import('./components/BaseForm.vue')['default']
    ChatView: typeof import('./components/ChatView.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageList: typeof import('./components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendInputBox: typeof import('./components/SendInputBox.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
